#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HR")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region 擴充性方法定義
  partial void OnCreated();
  partial void InsertPerson(Person instance);
  partial void UpdatePerson(Person instance);
  partial void DeletePerson(Person instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["HRConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Person> Person
	{
		get
		{
			return this.GetTable<Person>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Person")]
public partial class Person : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _Wid;
	
	private string _Id;
	
	private string _C_Name;
	
	private string _E_Name;
	
	private string _Photo;
	
	private string _Sex;
	
	private string _Did;
	
	private string _RoleClass_Id;
	
	private string _JOBCODE;
	
	private System.Nullable<int> _RoleLevel_id;
	
	private string _Tel1;
	
	private string _Tel2;
	
	private string _Tel3;
	
	private string _Email;
	
	private string _Msn;
	
	private string _Skype;
	
	private string _Remark;
	
	private string _Status;
	
	private string _Onboard_Date;
	
	private string _Birthday;
	
	private string _C_Zip;
	
	private string _C_Addr;
	
	private string _P_Zip;
	
	private string _P_Addr;
	
	private string _Is_Married;
	
	private string _Emergency_Contact;
	
	private string _Emergency_Contact_Tel;
	
	private string _School_Level;
	
	private string _School;
	
	private string _Leave_Date;
	
	private string _Leave_Reason;
	
	private System.Nullable<int> _Show_Index;
	
	private string _Contract_SDate;
	
	private string _Contract_EDate;
	
	private System.Nullable<decimal> _WorkYears;
	
	private string _JccCompanyName;
	
	private string _Cre_Usr;
	
	private System.Nullable<System.DateTime> _Cre_Date;
	
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnWidChanging(string value);
    partial void OnWidChanged();
    partial void OnIdChanging(string value);
    partial void OnIdChanged();
    partial void OnC_NameChanging(string value);
    partial void OnC_NameChanged();
    partial void OnE_NameChanging(string value);
    partial void OnE_NameChanged();
    partial void OnPhotoChanging(string value);
    partial void OnPhotoChanged();
    partial void OnSexChanging(string value);
    partial void OnSexChanged();
    partial void OnDidChanging(string value);
    partial void OnDidChanged();
    partial void OnRoleClass_IdChanging(string value);
    partial void OnRoleClass_IdChanged();
    partial void OnJOBCODEChanging(string value);
    partial void OnJOBCODEChanged();
    partial void OnRoleLevel_idChanging(System.Nullable<int> value);
    partial void OnRoleLevel_idChanged();
    partial void OnTel1Changing(string value);
    partial void OnTel1Changed();
    partial void OnTel2Changing(string value);
    partial void OnTel2Changed();
    partial void OnTel3Changing(string value);
    partial void OnTel3Changed();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnMsnChanging(string value);
    partial void OnMsnChanged();
    partial void OnSkypeChanging(string value);
    partial void OnSkypeChanged();
    partial void OnRemarkChanging(string value);
    partial void OnRemarkChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    partial void OnOnboard_DateChanging(string value);
    partial void OnOnboard_DateChanged();
    partial void OnBirthdayChanging(string value);
    partial void OnBirthdayChanged();
    partial void OnC_ZipChanging(string value);
    partial void OnC_ZipChanged();
    partial void OnC_AddrChanging(string value);
    partial void OnC_AddrChanged();
    partial void OnP_ZipChanging(string value);
    partial void OnP_ZipChanged();
    partial void OnP_AddrChanging(string value);
    partial void OnP_AddrChanged();
    partial void OnIs_MarriedChanging(string value);
    partial void OnIs_MarriedChanged();
    partial void OnEmergency_ContactChanging(string value);
    partial void OnEmergency_ContactChanged();
    partial void OnEmergency_Contact_TelChanging(string value);
    partial void OnEmergency_Contact_TelChanged();
    partial void OnSchool_LevelChanging(string value);
    partial void OnSchool_LevelChanged();
    partial void OnSchoolChanging(string value);
    partial void OnSchoolChanged();
    partial void OnLeave_DateChanging(string value);
    partial void OnLeave_DateChanged();
    partial void OnLeave_ReasonChanging(string value);
    partial void OnLeave_ReasonChanged();
    partial void OnShow_IndexChanging(System.Nullable<int> value);
    partial void OnShow_IndexChanged();
    partial void OnContract_SDateChanging(string value);
    partial void OnContract_SDateChanged();
    partial void OnContract_EDateChanging(string value);
    partial void OnContract_EDateChanged();
    partial void OnWorkYearsChanging(System.Nullable<decimal> value);
    partial void OnWorkYearsChanged();
    partial void OnJccCompanyNameChanging(string value);
    partial void OnJccCompanyNameChanged();
    partial void OnCre_UsrChanging(string value);
    partial void OnCre_UsrChanged();
    partial void OnCre_DateChanging(System.Nullable<System.DateTime> value);
    partial void OnCre_DateChanged();
    #endregion
	
	public Person()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Wid", DbType="NVarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string Wid
	{
		get
		{
			return this._Wid;
		}
		set
		{
			if ((this._Wid != value))
			{
				this.OnWidChanging(value);
				this.SendPropertyChanging();
				this._Wid = value;
				this.SendPropertyChanged("Wid");
				this.OnWidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="NVarChar(30)")]
	public string Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_Name", DbType="NVarChar(50)")]
	public string C_Name
	{
		get
		{
			return this._C_Name;
		}
		set
		{
			if ((this._C_Name != value))
			{
				this.OnC_NameChanging(value);
				this.SendPropertyChanging();
				this._C_Name = value;
				this.SendPropertyChanged("C_Name");
				this.OnC_NameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_E_Name", DbType="NVarChar(50)")]
	public string E_Name
	{
		get
		{
			return this._E_Name;
		}
		set
		{
			if ((this._E_Name != value))
			{
				this.OnE_NameChanging(value);
				this.SendPropertyChanging();
				this._E_Name = value;
				this.SendPropertyChanged("E_Name");
				this.OnE_NameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Photo", DbType="NVarChar(50)")]
	public string Photo
	{
		get
		{
			return this._Photo;
		}
		set
		{
			if ((this._Photo != value))
			{
				this.OnPhotoChanging(value);
				this.SendPropertyChanging();
				this._Photo = value;
				this.SendPropertyChanged("Photo");
				this.OnPhotoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sex", DbType="NVarChar(2)")]
	public string Sex
	{
		get
		{
			return this._Sex;
		}
		set
		{
			if ((this._Sex != value))
			{
				this.OnSexChanging(value);
				this.SendPropertyChanging();
				this._Sex = value;
				this.SendPropertyChanged("Sex");
				this.OnSexChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Did", DbType="NVarChar(10)")]
	public string Did
	{
		get
		{
			return this._Did;
		}
		set
		{
			if ((this._Did != value))
			{
				this.OnDidChanging(value);
				this.SendPropertyChanging();
				this._Did = value;
				this.SendPropertyChanged("Did");
				this.OnDidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleClass_Id", DbType="NVarChar(10)")]
	public string RoleClass_Id
	{
		get
		{
			return this._RoleClass_Id;
		}
		set
		{
			if ((this._RoleClass_Id != value))
			{
				this.OnRoleClass_IdChanging(value);
				this.SendPropertyChanging();
				this._RoleClass_Id = value;
				this.SendPropertyChanged("RoleClass_Id");
				this.OnRoleClass_IdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JOBCODE", DbType="NVarChar(10)")]
	public string JOBCODE
	{
		get
		{
			return this._JOBCODE;
		}
		set
		{
			if ((this._JOBCODE != value))
			{
				this.OnJOBCODEChanging(value);
				this.SendPropertyChanging();
				this._JOBCODE = value;
				this.SendPropertyChanged("JOBCODE");
				this.OnJOBCODEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoleLevel_id", DbType="Int")]
	public System.Nullable<int> RoleLevel_id
	{
		get
		{
			return this._RoleLevel_id;
		}
		set
		{
			if ((this._RoleLevel_id != value))
			{
				this.OnRoleLevel_idChanging(value);
				this.SendPropertyChanging();
				this._RoleLevel_id = value;
				this.SendPropertyChanged("RoleLevel_id");
				this.OnRoleLevel_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tel1", DbType="NVarChar(50)")]
	public string Tel1
	{
		get
		{
			return this._Tel1;
		}
		set
		{
			if ((this._Tel1 != value))
			{
				this.OnTel1Changing(value);
				this.SendPropertyChanging();
				this._Tel1 = value;
				this.SendPropertyChanged("Tel1");
				this.OnTel1Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tel2", DbType="NVarChar(50)")]
	public string Tel2
	{
		get
		{
			return this._Tel2;
		}
		set
		{
			if ((this._Tel2 != value))
			{
				this.OnTel2Changing(value);
				this.SendPropertyChanging();
				this._Tel2 = value;
				this.SendPropertyChanged("Tel2");
				this.OnTel2Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tel3", DbType="NVarChar(150)")]
	public string Tel3
	{
		get
		{
			return this._Tel3;
		}
		set
		{
			if ((this._Tel3 != value))
			{
				this.OnTel3Changing(value);
				this.SendPropertyChanging();
				this._Tel3 = value;
				this.SendPropertyChanged("Tel3");
				this.OnTel3Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(50)")]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this.OnEmailChanging(value);
				this.SendPropertyChanging();
				this._Email = value;
				this.SendPropertyChanged("Email");
				this.OnEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Msn", DbType="NVarChar(50)")]
	public string Msn
	{
		get
		{
			return this._Msn;
		}
		set
		{
			if ((this._Msn != value))
			{
				this.OnMsnChanging(value);
				this.SendPropertyChanging();
				this._Msn = value;
				this.SendPropertyChanged("Msn");
				this.OnMsnChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Skype", DbType="NVarChar(50)")]
	public string Skype
	{
		get
		{
			return this._Skype;
		}
		set
		{
			if ((this._Skype != value))
			{
				this.OnSkypeChanging(value);
				this.SendPropertyChanging();
				this._Skype = value;
				this.SendPropertyChanged("Skype");
				this.OnSkypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remark", DbType="NVarChar(50)")]
	public string Remark
	{
		get
		{
			return this._Remark;
		}
		set
		{
			if ((this._Remark != value))
			{
				this.OnRemarkChanging(value);
				this.SendPropertyChanging();
				this._Remark = value;
				this.SendPropertyChanged("Remark");
				this.OnRemarkChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="NVarChar(2)")]
	public string Status
	{
		get
		{
			return this._Status;
		}
		set
		{
			if ((this._Status != value))
			{
				this.OnStatusChanging(value);
				this.SendPropertyChanging();
				this._Status = value;
				this.SendPropertyChanged("Status");
				this.OnStatusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Onboard_Date", DbType="NVarChar(10)")]
	public string Onboard_Date
	{
		get
		{
			return this._Onboard_Date;
		}
		set
		{
			if ((this._Onboard_Date != value))
			{
				this.OnOnboard_DateChanging(value);
				this.SendPropertyChanging();
				this._Onboard_Date = value;
				this.SendPropertyChanged("Onboard_Date");
				this.OnOnboard_DateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Birthday", DbType="NVarChar(10)")]
	public string Birthday
	{
		get
		{
			return this._Birthday;
		}
		set
		{
			if ((this._Birthday != value))
			{
				this.OnBirthdayChanging(value);
				this.SendPropertyChanging();
				this._Birthday = value;
				this.SendPropertyChanged("Birthday");
				this.OnBirthdayChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_Zip", DbType="NVarChar(30)")]
	public string C_Zip
	{
		get
		{
			return this._C_Zip;
		}
		set
		{
			if ((this._C_Zip != value))
			{
				this.OnC_ZipChanging(value);
				this.SendPropertyChanging();
				this._C_Zip = value;
				this.SendPropertyChanged("C_Zip");
				this.OnC_ZipChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C_Addr", DbType="NVarChar(100)")]
	public string C_Addr
	{
		get
		{
			return this._C_Addr;
		}
		set
		{
			if ((this._C_Addr != value))
			{
				this.OnC_AddrChanging(value);
				this.SendPropertyChanging();
				this._C_Addr = value;
				this.SendPropertyChanged("C_Addr");
				this.OnC_AddrChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_Zip", DbType="NVarChar(30)")]
	public string P_Zip
	{
		get
		{
			return this._P_Zip;
		}
		set
		{
			if ((this._P_Zip != value))
			{
				this.OnP_ZipChanging(value);
				this.SendPropertyChanging();
				this._P_Zip = value;
				this.SendPropertyChanged("P_Zip");
				this.OnP_ZipChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P_Addr", DbType="NVarChar(100)")]
	public string P_Addr
	{
		get
		{
			return this._P_Addr;
		}
		set
		{
			if ((this._P_Addr != value))
			{
				this.OnP_AddrChanging(value);
				this.SendPropertyChanging();
				this._P_Addr = value;
				this.SendPropertyChanged("P_Addr");
				this.OnP_AddrChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Is_Married", DbType="NVarChar(2)")]
	public string Is_Married
	{
		get
		{
			return this._Is_Married;
		}
		set
		{
			if ((this._Is_Married != value))
			{
				this.OnIs_MarriedChanging(value);
				this.SendPropertyChanging();
				this._Is_Married = value;
				this.SendPropertyChanged("Is_Married");
				this.OnIs_MarriedChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emergency_Contact", DbType="NVarChar(50)")]
	public string Emergency_Contact
	{
		get
		{
			return this._Emergency_Contact;
		}
		set
		{
			if ((this._Emergency_Contact != value))
			{
				this.OnEmergency_ContactChanging(value);
				this.SendPropertyChanging();
				this._Emergency_Contact = value;
				this.SendPropertyChanged("Emergency_Contact");
				this.OnEmergency_ContactChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Emergency_Contact_Tel", DbType="NVarChar(100)")]
	public string Emergency_Contact_Tel
	{
		get
		{
			return this._Emergency_Contact_Tel;
		}
		set
		{
			if ((this._Emergency_Contact_Tel != value))
			{
				this.OnEmergency_Contact_TelChanging(value);
				this.SendPropertyChanging();
				this._Emergency_Contact_Tel = value;
				this.SendPropertyChanged("Emergency_Contact_Tel");
				this.OnEmergency_Contact_TelChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_School_Level", DbType="NVarChar(2)")]
	public string School_Level
	{
		get
		{
			return this._School_Level;
		}
		set
		{
			if ((this._School_Level != value))
			{
				this.OnSchool_LevelChanging(value);
				this.SendPropertyChanging();
				this._School_Level = value;
				this.SendPropertyChanged("School_Level");
				this.OnSchool_LevelChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_School", DbType="NVarChar(100)")]
	public string School
	{
		get
		{
			return this._School;
		}
		set
		{
			if ((this._School != value))
			{
				this.OnSchoolChanging(value);
				this.SendPropertyChanging();
				this._School = value;
				this.SendPropertyChanged("School");
				this.OnSchoolChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Leave_Date", DbType="NVarChar(10)")]
	public string Leave_Date
	{
		get
		{
			return this._Leave_Date;
		}
		set
		{
			if ((this._Leave_Date != value))
			{
				this.OnLeave_DateChanging(value);
				this.SendPropertyChanging();
				this._Leave_Date = value;
				this.SendPropertyChanged("Leave_Date");
				this.OnLeave_DateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Leave_Reason", DbType="NVarChar(100)")]
	public string Leave_Reason
	{
		get
		{
			return this._Leave_Reason;
		}
		set
		{
			if ((this._Leave_Reason != value))
			{
				this.OnLeave_ReasonChanging(value);
				this.SendPropertyChanging();
				this._Leave_Reason = value;
				this.SendPropertyChanged("Leave_Reason");
				this.OnLeave_ReasonChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Show_Index", DbType="Int")]
	public System.Nullable<int> Show_Index
	{
		get
		{
			return this._Show_Index;
		}
		set
		{
			if ((this._Show_Index != value))
			{
				this.OnShow_IndexChanging(value);
				this.SendPropertyChanging();
				this._Show_Index = value;
				this.SendPropertyChanged("Show_Index");
				this.OnShow_IndexChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contract_SDate", DbType="NVarChar(10)")]
	public string Contract_SDate
	{
		get
		{
			return this._Contract_SDate;
		}
		set
		{
			if ((this._Contract_SDate != value))
			{
				this.OnContract_SDateChanging(value);
				this.SendPropertyChanging();
				this._Contract_SDate = value;
				this.SendPropertyChanged("Contract_SDate");
				this.OnContract_SDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contract_EDate", DbType="NVarChar(10)")]
	public string Contract_EDate
	{
		get
		{
			return this._Contract_EDate;
		}
		set
		{
			if ((this._Contract_EDate != value))
			{
				this.OnContract_EDateChanging(value);
				this.SendPropertyChanging();
				this._Contract_EDate = value;
				this.SendPropertyChanged("Contract_EDate");
				this.OnContract_EDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WorkYears", DbType="Decimal(18,1)")]
	public System.Nullable<decimal> WorkYears
	{
		get
		{
			return this._WorkYears;
		}
		set
		{
			if ((this._WorkYears != value))
			{
				this.OnWorkYearsChanging(value);
				this.SendPropertyChanging();
				this._WorkYears = value;
				this.SendPropertyChanged("WorkYears");
				this.OnWorkYearsChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JccCompanyName", DbType="NVarChar(30)")]
	public string JccCompanyName
	{
		get
		{
			return this._JccCompanyName;
		}
		set
		{
			if ((this._JccCompanyName != value))
			{
				this.OnJccCompanyNameChanging(value);
				this.SendPropertyChanging();
				this._JccCompanyName = value;
				this.SendPropertyChanged("JccCompanyName");
				this.OnJccCompanyNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cre_Usr", DbType="NVarChar(30)")]
	public string Cre_Usr
	{
		get
		{
			return this._Cre_Usr;
		}
		set
		{
			if ((this._Cre_Usr != value))
			{
				this.OnCre_UsrChanging(value);
				this.SendPropertyChanging();
				this._Cre_Usr = value;
				this.SendPropertyChanged("Cre_Usr");
				this.OnCre_UsrChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cre_Date", DbType="DateTime")]
	public System.Nullable<System.DateTime> Cre_Date
	{
		get
		{
			return this._Cre_Date;
		}
		set
		{
			if ((this._Cre_Date != value))
			{
				this.OnCre_DateChanging(value);
				this.SendPropertyChanging();
				this._Cre_Date = value;
				this.SendPropertyChanged("Cre_Date");
				this.OnCre_DateChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
